### ISSUE TITLE
Add API using Django REST Framework.

### ISSUE THREAD

**Issue by proofit404** [dry-python/bookshelf#7]
- Reuse `implemented` module.
- Add `api` package with rest framework views.
- Add `permissions` package with rest framework permissions.
- Maybe use https://github.com/django-guardian/django-guardian/
- Maybe use https://github.com/carltongibson/django-filter

**Comment by simkimsia** [comment]
I'm looking at the readme for returns and i notice a short example abt using results container for a typical django api endpoint. So I m interested more abt how to apply dry-python stuff esp returns in a DRF context

**Comment by proofit404** [comment]
cc @sobolevn

**Comment by sobolevn** [comment]
@simkimsia awesome to hear that! You can also check out https://github.com/typeddjango

I think that this project is dedicated to `stories` and `dependencies`. I don't think that mixing these libraries together is a good idea. 

Currently, there's no showcase project for `returns`. I will appreciate any help on this subject.

**Comment by simkimsia** [comment]
@sobolevn Sorry I don't check my mentions in GitHub as often hence the delay

> You can also check out https://github.com/typeddjango

Do you use this?

> Currently, there's no showcase project for returns. I will appreciate any help on this subject.

What help do you need?

**Comment by sobolevn** [comment]
@simkimsia of course I do 🙂 
Example: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L114

You can probably show you own way of using `returns` and ask questions you have about it. It would totally help us!

**Comment by simkimsia** [comment]
> You can probably show you own way of using returns and ask questions you have about it. It would totally help us!

I'll do this. But won't be so soon as I'm still experimenting with mappers on my downtime while working on my deadlines during working hours.
